<a href="https://colab.research.google.com/github/Aslamhowlader/Python-Programming/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''. Array Creation

NumPy arrays can be created in many ways:

np.array() → convert list to array
np.zeros(shape) → all 0s
np.ones(shape) → all 1s
np.empty(shape) → uninitialized values
np.arange(start, stop, step) → range-based array
np.linspace(start, stop, num) → equal intervals
np.random.random(n) → random floats (0–1)
np.random.randint(low, high, size) → random integers
===============================================================
2. Array Shapes & Properties
a.shape → dimensions of array
a.ndim → number of dimensions
a.size → total elements
a.dtype → data type
a.reshape() → change shape
==============================================
3. Indexing & Slicing
1D:
a[start:stop:step]
Negative indexing: a[-1]
Reverse: a[::-1]
2D:
a[row, col]
a[row, :] → full row
a[:, col] → full column
Submatrix slicing: a[r1:r2, c1:c2]
Boolean indexing:
a[a > 10]
a[(a > 10) & (a % 2 == 0)]
========================================
4. Array Operations
Scalar operations:
a + 5, a - 5, a * 2, a / 2
Comparison:
a > 5, a == 10, etc. (returns boolean array)
=========================================
5. Mathematical Functions
np.sum()
np.prod()
np.mean()
np.median()
np.std()
np.var()
np.min(), np.max()
Axis concept:
axis=0 → column-wise
axis=1 → row-wise
==============================================
6. Trigonometric Functions
np.sin()
np.cos()
np.tan()

(operate element-wise on arrays)
============================================

7. Exponential & Log Functions
np.exp() → e^x
np.log() → natural log
np.log10() → base-10 log
np.sqrt() → square root

⚠️ log only works for positive values
=====================================================

8. Linear Algebra
np.dot(A, B) → matrix multiplication
(Requires compatible shapes)
==========================================
9. Set Operations
np.union1d() → union
np.intersect1d() → intersection
np.setdiff1d() → difference
np.setxor1d() → symmetric difference
===========================================
10. Array Manipulation
np.concatenate() → join arrays
np.vstack() → vertical stack
np.hstack() → horizontal stack
np.split() → split array
np.expand_dims() → add dimension
np.flip() → reverse array
===============================================
11. Utility Functions
np.where() → conditional selection
np.unique() → unique values
np.isin() → membership check
np.percentile() → percentile value
np.clip() → limit values
np.put() → modify elements by index
=====================================================
12. Sorting & Searching
np.sort() → sort values
np.argsort() → sorted indices
np.argmax() → index of max
np.argmin() → index of min
======================================
13. Plotting (Matplotlib with NumPy)

You plotted:

y = x
y = x²
y = sin(x)
y = x log(x)

Key idea:

np.linspace() creates smooth x-axis values
matplotlib visualizes NumPy computations

========================================

14. Key Concepts You Practiced
Vectorized operations (no loops)
Broadcasting
Axis-based computation
Boolean filtering
Matrix operations
Data reshaping'''

In [ ]:
import numpy as np
from babel.dates import parse_time
from mistune.toc import normalize_toc_item

arr=[1,2,3,4,5,6,7]
arr

[1, 2, 3, 4, 5, 6, 7]

In [ ]:
np.array(arr)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr_2d=[[1,2,3],[4,5,6],[7,8,4]]
arr_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 4]]

1. Array Creation Functions
  | Function             | Work                 |
| -------------------- | -------------------- |
| `np.array()`         | create array         |
| `np.zeros()`         | array with 0         |
| `np.ones()`          | array with 1         |
| `np.empty()`         | empty array          |
| `np.arange()`        | range array          |
| `np.linspace()`      | equal intervals      |
| `np.random.random()` | random float numbers |


In [ ]:
np.array(arr_2d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 4]])

In [ ]:
# np.arange(start, stop, step)
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
'''3 → number of blocks (depth)
    5 → rows in each block
       4 → columns in each row

So it creates a 3 × 5 × 4 tensor (3D array) filled with zeros.'''



np.zeros([3,5,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
'''5 → number of rows
     4 → number of columns
fills everything with 1.0 (float by default)
'''

np.ones([5,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
'''

 It divides the interval 10 → 20 into 4 equal gaps (because 5 points create 4 intervals):
  (20−10)/(5−1)=2.5
 '''


np.linspace(start=10,stop=100,num=5)

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [ ]:
np.arange(0,20,2).reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [ ]:
np.ones([3,5],dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.random.random(10)

array([0.34530657, 0.66902431, 0.24252801, 0.90043686, 0.16541255,
       0.32562423, 0.11102434, 0.66677195, 0.46021235, 0.43939044])

In [ ]:
a1=np.random.randint(0,10,15).reshape(3,5)
a1

array([[9, 9, 4, 1, 4],
       [2, 4, 8, 3, 1],
       [2, 5, 5, 0, 3]], dtype=int32)

Shape Functions
  | Function      | Work           |
| ------------- | -------------- |
| `a.shape`     | array size     |
| `a.reshape()` | change shape   |
| `a.ndim`      | dimensions     |
| `a.size`      | total elements |
| `a.dtype`     | data type      |


In [ ]:
a1.ndim

2

In [ ]:
a1.shape

(3, 5)

In [ ]:
a1.size

15

In [ ]:
a1.dtype

dtype('int32')

In [ ]:
a2=np.arange(12).reshape(3,4)
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# Scalar Operations
# Arithmatice
print("Add \n",a2+4)
print("sub\n",a2-5)
print("Mul\n",a2*3)
print("div\n",a2/2)

Add 
 [[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
sub
 [[-5 -4 -3 -2]
 [-1  0  1  2]
 [ 3  4  5  6]]
Mul
 [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]
div
 [[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


In [ ]:
print(a2>5)
print("-----------------------------------------------------")
print(a2<5)
print("------------------------------------------------------")
print(a2>=5)
print("------------------------------------------------------")
print(a2<=5)
print("------------------------------------------------------")

print(a2==5)
print("------------------------------------------------------")

print(a2!=5)
print("------------------------------------------------------")


[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
-----------------------------------------------------
[[ True  True  True  True]
 [ True False False False]
 [False False False False]]
------------------------------------------------------
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
------------------------------------------------------
[[ True  True  True  True]
 [ True  True False False]
 [False False False False]]
------------------------------------------------------
[[False False False False]
 [False  True False False]
 [False False False False]]
------------------------------------------------------
[[ True  True  True  True]
 [ True False  True  True]
 [ True  True  True  True]]
------------------------------------------------------


2. Mathematical Functions
  | Function      | Work               |
| ------------- | ------------------ |
| `np.sum()`    | total sum          |
| `np.prod()`   | multiplication     |
| `np.mean()`   | average            |
| `np.median()` | middle value       |
| `np.std()`    | standard deviation |
| `np.var()`    | variance           |
| `np.min()`    | minimum            |
| `np.max()`    | maximum            |


In [ ]:
a0=np.arange(25)
a0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
a1=np.arange(12).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2=np.arange(12,24).reshape(4,3)
a2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

**min/max/prod/sum**

In [ ]:
# 1D Array
print(np.min(a0))
print(np.max(a0))
print(np.sum(a0))
print(np.prod(a0))

0
24
300
0


In [ ]:
# 2D Array colomn_axis=0,row_axis=1
print(a2)
print("Colomn_axis_min :",np.min(a2,axis=0))
print("Row_axis_min :",np.min(a2,axis=1))


[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Colomn_axis_min : [12 13 14]
Colomn_axis_min : [12 15 18 21]


In [ ]:
# 2D Array colomn_axis=0,row_axis=1
print(a2)
print("Colomn_axis_max :",np.max(a2,axis=0))
print("Row_axis_max :",np.max(a2,axis=1))

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Colomn_axis_max : [21 22 23]
Row_axis_max : [14 17 20 23]


In [ ]:
# 2D Array colomn_axis=0,row_axis=1
print(a2)
print("Colomn_axis_sum :",np.sum(a2,axis=0))
print("Row_axis_sum :",np.sum(a2,axis=1))

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Colomn_axis_sum : [66 70 74]
Row_axis_sum : [39 48 57 66]


In [ ]:
# 2D Array colomn_axis=0,row_axis=1
print(a2)
print("Colomn_axis_prod :",np.prod(a2,axis=0))
print("Row_axis_prod :",np.prod(a2,axis=1))

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Colomn_axis_prod : [ 68040  86944 109480]
Row_axis_prod : [ 2184  4080  6840 10626]


In [ ]:
# 2D Array min/max/sum/prod
print(np.min(a2))
print(np.max(a2))
print(np.sum(a2))
print(np.prod(a2))

12
23
210
647647525324800


# 2D Array mean/mediam/mod/std/var

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# 2D Array mean/mediam/mod/std/var

print(a2)
print(np.mean(a2))
print(np.median(a2))

print(np.std(a2))
print(np.var(a2))

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
17.5
17.5
3.452052529534663
11.916666666666666


In [ ]:
# 2D Array mean/mediam/mod/std/var axis colomn=0,

print(a2)
print(np.mean(a2,axis=0))
print(np.median(a2,axis=0))

print(np.std(a2,axis=0))
print(np.var(a2,axis=0))

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[16.5 17.5 18.5]
[16.5 17.5 18.5]
[3.35410197 3.35410197 3.35410197]
[11.25 11.25 11.25]


In [ ]:
print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))


[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]]
[[ 1.          0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029  0.75390225]
 [-0.14550003 -0.91113026 -0.83907153  0.0044257 ]]
[[ 0.00000000e+00  1.55740772e+00 -2.18503986e+00 -1.42546543e-01]
 [ 1.15782128e+00 -3.38051501e+00 -2.91006191e-01  8.71447983e-01]
 [-6.79971146e+00 -4.52315659e-01  6.48360827e-01 -2.25950846e+02]]


In [ ]:
# 2D Array mean/mediam/mod/std/var axis Row=1

print(a2)
print(np.mean(a2,axis=1))
print(np.median(a2,axis=1))

print(np.std(a2,axis=1))
print(np.var(a2,axis=1))

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[13. 16. 19. 22.]
[13. 16. 19. 22.]
[0.81649658 0.81649658 0.81649658 0.81649658]
[0.66666667 0.66666667 0.66666667 0.66666667]


3. Trigonometric Functions
 | Function   | Work    |
| ---------- | ------- |
| `np.sin()` | sine    |
| `np.cos()` | cosine  |
| `np.tan()` | tangent |


4. Exponential & Log Functions
  | Function     | Work        |
| ------------ | ----------- |
| `np.exp()`   | exponential |
| `np.log()`   | natural log |
| `np.log10()` | log base 10 |
| `np.sqrt()`  | square root |


In [ ]:
print(np.log(a2))
print(np.exp(a2))


[[2.48490665 2.56494936 2.63905733]
 [2.7080502  2.77258872 2.83321334]
 [2.89037176 2.94443898 2.99573227]
 [3.04452244 3.09104245 3.13549422]]
[[1.62754791e+05 4.42413392e+05 1.20260428e+06]
 [3.26901737e+06 8.88611052e+06 2.41549528e+07]
 [6.56599691e+07 1.78482301e+08 4.85165195e+08]
 [1.31881573e+09 3.58491285e+09 9.74480345e+09]]


dot

In [ ]:
print(np.dot(a1,a2))

[[114 120 126]
 [378 400 422]
 [642 680 718]]


Set Funcation
 1.Unionid
 2.intersectid
 3.setdiffid
 4.setxorid
 5.inid



In [ ]:
m = [1,2,3,4,5]
n = [6,2,7,4,8]

In [ ]:
print(np.union1d(m,n))
print(np.intersect1d(m,n))
print(np.setxor1d(m,n))
print(np.setxor1d(m,n))

[1 2 3 4 5 6 7 8]
[2 4]
[1 3 5 6 7 8]
[1 3 5 6 7 8]
